export type SlideConfig = {
  id?: string;
  slotName?: string;
  type?: 'image' | 'component';
  image?: string;
  imageAssetId?: string;
  imageUrl?: string;
  src?: string;
  alt?: string;
  componentId?: string;
  componentName?: string;
  componentProps?: Record<string, unknown>;
  caption?: string;
  hash?: string;
};

export type SwiperEffect = 'slide' | 'fade' | 'cube' | 'coverflow' | 'flip' | 'cards' | 'creative';
export type PaginationType = 'bullets' | 'fraction' | 'progressbar';

export type SwiperCarouselProps = {
  paginationEnabled?: boolean;
  paginationType?: PaginationType;
  paginationClickable?: boolean;
  navigationEnabled?: boolean;
  navigationHideOnClick?: boolean;
  scrollbarEnabled?: boolean;
  scrollbarDraggable?: boolean;
  scrollbarHide?: boolean;
  scrollbarSnapOnRelease?: boolean;
  styleMode?: 'swiper' | 'ravium';
  autoplayDelayMs?: number;
  autoplayDisableOnInteraction?: boolean;
  autoplayPauseOnMouseEnter?: boolean;
  autoplayReverseDirection?: boolean;
  autoplayStopOnLastSlide?: boolean;
  slidesPerView?: number;
  slidesPerGroup?: number;
  direction?: 'horizontal' | 'vertical';
  loopEnabled?: boolean;
  rewindEnabled?: boolean;
  centeredSlides?: boolean;
  freeModeEnabled?: boolean;
  freeModeMomentum?: boolean;
  freeModeMomentumRatio?: number;
  freeModeSticky?: boolean;
  mousewheelEnabled?: boolean;
  mousewheelForceToAxis?: boolean;
  mousewheelInvert?: boolean;
  mousewheelSensitivity?: number;
  keyboardEnabled?: boolean;
  keyboardOnlyInViewport?: boolean;
  keyboardPageUpDown?: boolean;
  a11yEnabled?: boolean;
  zoomEnabled?: boolean;
  zoomMaxRatio?: number;
  zoomMinRatio?: number;
  zoomToggle?: boolean;
  virtualEnabled?: boolean;
  parallaxEnabled?: boolean;
  parallaxOffset?: string;
  hashNavigationEnabled?: boolean;
  hashNavigationWatchState?: boolean;
  hashNavigationReplaceState?: boolean;
  historyEnabled?: boolean;
  historyKey?: string;
  historyReplaceState?: boolean;
  historyKeepQuery?: boolean;
  effect?: SwiperEffect;
  effectRotate?: number;
  effectDepth?: number;
  effectModifier?: number;
  effectShadows?: boolean;
  speed?: number;
  autoHeight?: boolean;
  grabCursor?: boolean;
  cssMode?: boolean;
  gridRows?: number;
  allowTouchMove?: boolean;
  simulateTouch?: boolean;
  touchRatio?: number;
  touchAngle?: number;
  threshold?: number;
  slides?: SlideConfig[];
  spaceBetween?: number;
  slideBackgroundColor?: string;
  slideBorderRadius?: string;
  slideBorderWidth?: string;
  slideBorderStyle?: 'none' | 'solid' | 'dashed' | 'dotted';
  slideBorderColor?: string;
  slidePadding?: string;
  captionColor?: string;
  captionPadding?: string;
  captionFontSize?: string;
  captionFontWeight?: string;
  imageFit?: 'cover' | 'contain';
};
